version: '3.8'

services:
  mysql:
    image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/mysql:8.0.30-8.6
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: danny
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./backup:/backup
      - ./entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh
    command: [ "/bin/bash", "/docker-entrypoint-initdb.d/entrypoint.sh" ]

  redis:
    image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/redis:5.0.3-8.6
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

  app:
    image: my-java-app
    container_name: trade-admin10
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/mydb
      SPRING_DATASOURCE_USERNAME: danny
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    ports:
      - "8080:8080"
    networks:
      - backend
networks:
  backend: